# Generated by Django 4.2.2 on 2023-08-08 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
