# Generated by Django 4.2.2 on 2023-07-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
