# Generated by Django 4.2.2 on 2023-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
