# Generated by Django 4.1.4 on 2023-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_pdf_options_alter_resume_pdf_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_pdf',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
